Add paper on AutoPrognosis https://journals.plos.org/plosone/article/…
ayevh/ayevh pull request #1
Opened 2019-12-13 06:25 UTC by jrlvarghese

…file?id=10.1371/journal.pone.0213653&type=printable

Add a AutoPrognosis.docx file, detailing about AutoPrognosis

2019-12-20 08:00 UTC, obonac commented
Hi @jrlvarghese 

Thank you for the pull request.

As of now, the contents of the pull request require some modifications before we can merge it with upstream.

1. Kindly do not include copyrighted material in any submissions to AyeAI and related repositories unless they one of the open source licences, or are under Creative Commons Sharealike attribution. Please remove the pdf file from your fork and then raise the pull request again.

Explanation: Most scientific publications, including free access ones have strict rules against distribution of their copyrighted material. In case they allow redistribution, please point a link to the same in your main write-up (the .md file)

2. For images, the illustrations must not have come from a copyrighted source without rights for distribution. Creative Common SA (CC-SA) attributed version are acceptable. In such cases please include the URL from where it was ascertained that the material is CC-SA attributed.

3. In case of a citation, please use any of the various internet archiving services, shorten the resulting url on bit.ly and point to that link as the reference.

Please let us know if you have any queries.

Kind regards,
Abhishek

2019-12-20 08:02 UTC, obonac commented on AutoPrognosis.md
> +# What is AutoPrognosis?
Kindly refer source of this definition

2019-12-20 08:04 UTC, obonac commented on AutoPrognosis.md
> +![schematic image](https://github.com/jrlvarghese/Ayevh/blob/master/autoprognosis_schematic.PNG)
Kindly refer source of this image. In case it is your drawing, then kindly mention as such in reply.

2019-12-20 08:05 UTC, obonac commented on AutoPrognosis.md
> +  * 7 imputation algorithms
Where are these numbers sourced from?

2019-12-20 08:05 UTC, obonac commented on AutoPrognosis.md
> +Out of 4801 CVD cases recorded within 5 years baseline, AutoPrognosis could predict 368 more cases compared to Framingham score.
Kindly cite the source

2019-12-20 08:09 UTC, obonac requested changes
Kindly resubmit after removing pdf unless it is under any license permitting free distribution.

All material sourced from other sites must be duly provided with references, and they must only be added if allowed as per license.

2019-12-21 10:01 UTC, jrlvarghese reviewed
Updated

2019-12-21 10:01 UTC, jrlvarghese commented on AutoPrognosis.md
> +# What is AutoPrognosis?
Noted your suggestions. I will update those reference.

2019-12-21 10:36 UTC, closed without merging